### ISSUE TITLE
Issue with inject_frb.py

### ISSUE THREAD

**Issue by parulj3795** [liamconnor/injectfrb#1]
Even though sigproc is properly installed, I get the following error. I ran the test_*.py files and they work properly.
$ python inject_gaussian_fil.py --nfrb 5 --simulator injectfrb --dm_min 100. --dm_max 100. --outdir outputdir --upchan_factor 1 --upsamp_factor 1
Either could not load sigproc or create filterbank
sh: 1: inject_frb.py: not found

Also python2 inject_frb.py gives me the following error -
Traceback (most recent call last):
  File "inject_frb.py", line 418, in <module>
    fn_fil = args[0]
IndexError: list index out of range

**Comment by parulj3795** [comment]
> Even though sigproc is properly installed, I get the following error. I ran the test_*.py files and they work properly.
> $ python inject_gaussian_fil.py --nfrb 5 --simulator injectfrb --dm_min 100. --dm_max 100. --outdir outputdir --upchan_factor 1 --upsamp_factor 1
> Either could not load sigproc or create filterbank
> sh: 1: inject_frb.py: not found
> 
> Also python2 inject_frb.py gives me the following error -
> Traceback (most recent call last):
> File "inject_frb.py", line 418, in 
> fn_fil = args[0]
> IndexError: list index out of range
